[core_settings]
# The CI already timestamps the logs
log_timestamp = false
log_error_details = true

[listener]
listener_type = "DomainSocket"
# The timeout needs to be smaller than the test client timeout (five seconds) as it is testing
# that the service does not hang for very big values of body or authentication length.
timeout = 3000 # in milliseconds
socket_path = "/tmp/parsec.sock"

[authenticator]
auth_type = "Direct"

[[key_manager]]
name = "on-disk-manager"
manager_type = "OnDisk"
store_path = "/tmp/mappings"

[[provider]]
provider_type = "Tpm"
key_info_manager = "on-disk-manager"
tcti = "mssim:host=127.0.0.1,port=2321"
owner_hierarchy_auth = ""
endorsement_hierarchy_auth = ""
root_of_trust = { pcr_list = [0,1,2], pcr_hash_alg = "Sha256" }
attesting_key = "Ecc"